# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: map(learn, world)
email: to.be.impressive@gmail.com
description: >
  Stay simple, stay naive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kigawas.github.io" # the base hostname & protocol for your site
twitter_username: kigawas
github_username:  kigawas

# Build settings
markdown: kramdown
# paginate
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 4
# sass
sass:
  sass_dir: assets/sass

#default
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: code
      comments: true
